spring:
  datasource:
#    url: jdbc:mysql://144.34.178.81:3306/stupidoc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: yao
#    password: helloyao
      url: jdbc:mysql://localhost:3306/stupidoc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
